version: '3'
services:
  express-app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    env_file:
      - .env
  react-app:
    build:
      context: ../seafood-chat
      args:
        VITE_API_URL: "http://13.51.160.180:5000"
    ports:
      - '80:80'
volumes:
  seafood-chat: